<?php
$lang = array(
    'has_bind' => '账号已经绑定',
    'bind_success' => '绑定成功',
    'bind_cancel_success' => '绑定取消成功',
    'please_confirm' => '请求已推送到您的洋葱App,请打开确认',
    'login_success' => '登录成功',
    'login_failed' => '登录失败',
    'unbind' => '您还未绑定洋葱',
    'scan_to_bind' => '请扫二维码进行授权绑定',
    'unknow_error' => '未知错误',
    'error_code'=> array(
        '200' => '请求成功',
        '400' => '请求参数格式错误',
        '401' => 'app 状态错误',
        '402' => 'app_id错误',
        '403' => '请求签名错误',
        '404' => '请求API不存在',
        '405' => '请求方法错误',
        '406' => '不在应用白名单里',
        '407' => '30s离线验证太多次，请重新打开离线验证页面',
        '500' => '洋葱系统服务错误',
        '501' => '生成二维码图片失败',
        '600' => '动态验证码错误',
        '601' => '用户拒绝授权',
        '602' => '等待用户响应超时，可重试',
        '603' => '等待用户响应超时，不可重试',
        '604' => '用户或event_id不存在',
        '605' => '用户未开启该验证类型'
    ),
    'template' => array(
        'bind_secken' => '绑定洋葱授权',
        'get_qrcode_error' => '获取绑定二维码错误',
        'close' => '关闭',
        'click_to_bind' => '点击按钮，立刻绑定洋葱授权',
        'click_to_unbind' => '点击按钮，解除洋葱绑定',
        'unbind' => '还还没有绑定',
        'has_bind' => '你已经绑定了，点击可以重新绑定或点击这里',
        'cancel_bind' => '取消绑定',
        'use_secken' => '使用洋葱授权，您可以...',
        'use_secken_to_login' => '用洋葱授权轻松登录',
        'no_need_to_remember_password' => '无需记住本站的帐号和密码，随时使用洋葱授权轻松登录',
        'certification' => '正在进行一键授权验证...',
        'secken_login' => '洋葱扫一扫登录',
        'secken_login_1' => '洋葱登录，快速安全'
    )
);
